# Uncomment the next line to define a global platform for your project
# platform :ios, '15.4'

target 'GithubUserProfile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubUserProfile
pod 'Kingfisher', '~> 8.0'


  target 'GithubUserProfileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubUserProfileUITests' do
    # Pods for testing
inherit! :search_paths
  end

end
